markdown_extensions:
- sane_lists
- smarty
- toc:
    permalink: true
nav:
- Home:
  - The Bitflow Project: https://bitflow.readthedocs.io/en/latest/
  - Data Sources, Sinks and Format: https://bitflow.readthedocs.io/en/latest/data-format/
  - Core functionality: https://bitflow.readthedocs.io/en/latest/core-functionality/
  - Bitflow Script: https://bitflow.readthedocs.io/projects/bitflow-antlr-grammars/en/latest/bitflow-script/
  - Naming Conventions: https://bitflow.readthedocs.io/en/latest/naming/
  - Development Process: https://bitflow.readthedocs.io/en/latest/development/
- Implementations:
  - go-bitflow: https://bitflow.readthedocs.io/projects/go-bitflow/en/latest/
  - bitflow4j: index.md
  - python-bitflow: https://bitflow.readthedocs.io/projects/python-bitflow/en/latest/
- Related Projects:
  - bitflow-collector: https://bitflow.readthedocs.io/projects/go-bitflow-collector/en/latest/
  - bitflow-coordinator (Github): https://github.com/bitflow-stream/bitflow-coordinator
  - bitflow-process-agent (Github): https://github.com/bitflow-stream/bitflow-process-agent
plugins:
- search
repo_url: https://github.com/bitflow-stream/bitflow4j
site_author: Florian Schmidt
site_description: Bitflow4j Documentation
site_name: Bitflow4j
theme: readthedocs
